[package]
name = "frive"
version = "0.1.0"
authors = ["Stewart Mackenzie <sjm@fractalide.com>"]
edition = "2018"

[dependencies]
libfractalide = { path = "../libfractalide" }
cursive = "0.14.0"
cursive-tabs = "0.4.2"
structopt = "0.3.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

